### ISSUE TITLE
192.168.1.1

### ISSUE THREAD

**Issue by Darskiy** [kyoto44/openwrt-ax6s#1]
👋После апгрейда пускает только через firefox, в остальных браузерах `ERR_CONNECTION_REFUSED`. Подскажите, пожалуйста, в чём может быть проблема ?
`RB03`

**Comment by kyoto44** [comment]
Возможно, это из-за замены nginx на uhttpd, но у меня всё норм. Попробуйте прошить начисто.

**Comment by Darskiy** [comment]
> Попробуйте прошить начисто.

Именно так всегда и делаю, во избежание потенциальных проблем.

**Comment by Darskiy** [comment]
Получилось пофиксить следующими командами:
```
opkg --force-maintainer --force-reinstall install uhttpd
service uhttpd restart
```

**Comment by Darskiy** [comment]
Получилось пофиксить следующими командами:
```
opkg --force-maintainer --force-reinstall install uhttpd
service uhttpd restart
```
